### ISSUE TITLE
Dark mode?

### ISSUE THREAD

**Issue by NovaViper** [drannex42/linux-utils#4]
Hey. I just started using the Firefox css with the Sidebery variant but it doesn't seem to support dark mode and looks very strange and is really hard to read when im using dark mode. Will there be any dark mode support?
![image](https://user-images.githubusercontent.com/7191115/125822752-def5d3a3-130e-45ad-8ed5-505d54d6dfc6.png)
![image](https://user-images.githubusercontent.com/7191115/125822802-fa2fc974-41a7-4924-9f45-fd5e5bfda3e8.png)

**Comment by drannex42** [comment]
Yes. I have been pressed for time lately and meant to have an update out last month for dark theme support. Will be out in the next week or so if I'm lucky! There has been a lot of interest in dark theme support.

**Comment by NovaViper** [comment]
Sweet! By any chance will there be a version that lets the sidebar sit on the right side of the screen?

**Comment by drannex42** [comment]
Long time coming, but custom theme support is enabled. Please see the ReadMe for details on changing values to fix your theme (there is not any auto theming yet).
