### ISSUE TITLE
Sidebery not working properly

### ISSUE THREAD

**Issue by c30ra** [drannex42/linux-utils#7]
Hello, i have some issue: tab text is still visible and i think the sidebar take to much space

**Comment by drannex42** [comment]
You implented the user Chrome.css to your Firefox profile?

Could you attach a screenshot?

**Comment by c30ra** [comment]
Yes, I've followed the guidelines, also imported the sidebery settings from your repo.
This is what i see
![immagine](https://user-images.githubusercontent.com/16150836/146042239-e72b221f-1704-44e1-9c13-466b5bb7177f.png)

It's just the sidebar being smaller, and not restyled when compressed

**Comment by drannex42** [comment]
Does it correct and align itself when you hover over the sidebar?

**Comment by c30ra** [comment]
yes

**Comment by drannex42** [comment]
While this may not fix the hover issue, I did just submit a fix for a few things in userChrome.css and in sideberry (primarily to add away to change font size using the settings panel, and to add theming for dark themes)

**Comment by c30ra** [comment]
Probably I've found the problem: I think that for my monitor/resolution, the minimum width of the sidebar should be 32px. At the end, I've ended up write my own css. Thanks anyway

**Comment by drannex42** [comment]
Have a great one @c30ra! I'll close this out then.
