### ISSUE TITLE
Sidebery Pinned Tab Adjustment Prevents Folding Tabs

### ISSUE THREAD

**Issue by bpoteryko** [drannex42/linux-utils#8]
In the most recent version, 2021.12.14, when applying the Sidebery settings, the functionality to expand/collapse tree tabs breaks, with the fold arrows refusing to appear.

I have tracked the issue down to the `z-index: 9` entry in the custom CSS segment of the sidebery-data.json file. Removing this line fixes the issue, and I see no other effects on the styling, though I'm not much of a CSS expert, myself.

**Comment by drannex42** [comment]
Good catch! I rarely use that feature and this is why it wasn't fixed earlier. Good call! I've submitted the patch and added it to the release notes. Thanks @bpoteryko! I'll close it out.
